# Generated by Django 2.2.8 on 2020-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
