# Generated by Django 2.2.8 on 2020-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='NEW', max_length=70, unique=True),
        ),
    ]
