# Generated by Django 2.2.8 on 2019-12-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20191223_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='domains.Company'),
        ),
    ]
