# Generated by Django 2.2.8 on 2019-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20191223_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='use_custom_address',
            field=models.BooleanField(default=False),
        ),
    ]
