# Generated by Django 2.2.8 on 2019-12-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191212_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pidgin',
            new_name='jabber_nick',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='pidgin',
            new_name='jabber',
        ),
    ]
